name: CI

on: [push]

jobs:
  OSX:

    runs-on: macOS-10.14

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    
    - name: Build and test
      run: |
        mkdir packages
        dotnet build
        dotnet test tests -v normal
